Added spark driver info to UI with alerts
dataflint/spark pull request #15
Opened 2024-09-11 10:38 UTC by DanielAronovich

Added spark driver info to the memory usage in the status and summary tabs
Added relevant alerts for driver over usage

2024-09-17 08:14 UTC, menishmueli requested changes

2024-09-19 13:10 UTC, DanielAronovich commented on spark-plugin/plugin/src/main/scala/org/apache/spark/dataflint/listener/model.scala
> +}
You need it as it fails without it, also the IcebergCommitWrapper has it

2024-09-22 08:04 UTC, menishmueli commented on spark-plugin/plugin/src/main/scala/org/apache/spark/dataflint/listener/model.scala
> +}
OK

2024-09-22 08:14 UTC, menishmueli commented on spark-ui/src/reducers/Alerts/MemoryAlertsReducer.ts
> +  }
you did not address this comment

2024-09-22 08:15 UTC, menishmueli commented on spark-ui/src/reducers/Alerts/MemoryAlertsReducer.ts
> +  if (driverMemory < MIN_DRIVER_MEMORY) {
please add a "done" next time you address a comment

2024-09-22 08:15 UTC, menishmueli commented on spark-ui/src/components/SummaryBar.tsx
>        </Grid>
please add a "done" comment or a plus icon next time you address a comment

2024-09-22 08:16 UTC, menishmueli commented on spark-ui/src/components/StatusBar.tsx
>          </Grid>
please add a "done" comment or a plus icon next time you address a comment

2024-09-22 08:17 UTC, menishmueli commented on spark-plugin/plugin/src/main/scala/org/apache/spark/dataflint/DataflintSparkUILoader.scala
>          if (isDatabricks) {
You now has if(isDatabricks) twice nested, please fix this

2024-09-23 06:36 UTC, menishmueli requested changes

2024-09-23 06:36 UTC, menishmueli commented on spark-ui/src/components/SummaryBar.tsx
> +              <Typography variant="body1" color="inherit" textAlign={"center"}>
when no data please hide the text

2024-09-23 06:36 UTC, menishmueli commented on spark-ui/src/components/StatusBar.tsx
> +  const driverMemoryUsagePercentage =
please use the calculatePercentage util I wrote

2024-09-23 06:36 UTC, menishmueli commented on spark-plugin/plugin/src/main/scala/org/apache/spark/dataflint/DataflintSparkUILoader.scala
> +      logInfo(s"Posted DataflintEnvironmentInfoEvent max driver memory: ${driverXmxBytes}")
please remove this log line from production

2024-09-23 06:36 UTC, menishmueli commented on spark-plugin/plugin/src/main/scala/org/apache/spark/dataflint/DataflintSparkUILoader.scala
> +        logInfo("Added DataflintDatabricksLiveListener to the Spark context")
please remove this line from production

2024-09-23 06:36 UTC, menishmueli commented on spark-ui/src/components/SummaryBar.tsx
> +  const driverMemoryUsage = driverExecutor?.memoryUsageBytes ?? 0;
please change memoryUsageBytes to use only on heap memory (+ executors)

2024-10-15 15:01 UTC, merged